### PR TITLE
Add Pagination component

### PR DESCRIPTION
**Pull request by jamescarlos**
Added the pagination component for use with the database component.

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks @jamescarlos! I'll want you, or me, or someone else to update this PR to show how to use pagination without Eloquent (in a separate route in this example, I'm guessing) before we merge.

Is that something you want to do? If not, no worries; I can either do it myself or ask someone else to do it; just wanted to ask you first. Thanks!

**Comment by jamescarlos** [comment]
@mattstauffer, I didn't think of it, but now it intrigues me. I'll try to check it out, but don't want to hold up the merge.

**Comment by mattstauffer** [comment]
No worries for me. If you want to be the one to do it but don’t want to
hold up the merge, maybe you can make a note in the README and the
component that it’s a half-complete component, and then we can merge?

**Comment by jamescarlos** [comment]
@mattstauffer I've added some notes for now. Thanks!

**Comment by mattstauffer** [comment]
Thanks @jamescarlos!

**Pull request merged**
