### PR TITLE
Fix Redis Cache 5.5

### PR DESCRIPTION
**Pull request by Rohiri**

### CODE REVIEW

**Comment by mattstauffer** [comment]
Could you explain this? Is the current 5.5 implementation entirely wrong or what more can we know about this PR?

**Comment by Rohiri** [comment]
1.  The Class use Illuminate\Redis\Database rename to Illuminate\Redis\RedisManager.
2. Redis manager construct expects 2 parameter driver and config array

Thanks for your work

**Comment by mattstauffer** [comment]
@Rohiri Thanks--I understand what the code does, I'm just curious why we have code in here that's broken :) I'll try out your code and the old code and see if I can parse through what's going on. Thanks for your PR!

**Comment by mattstauffer** [comment]
Thanks! I had to make a few modifications in order for it to work on my machine, but it does now. Thanks for catching this and fixing it!

**Pull request merged**
