### PR TITLE
chore: bump all laravel 6.0 components to 7.0

### PR DESCRIPTION
**Pull request by StephaneBour**

### CODE REVIEW

**Comment by StephaneBour** [comment]
close #144

**Comment by StephaneBour** [comment]
### Chore

* bump `illuminate/console` from 6.0 to 7.0 ([fe08ffd](https://github.com/StephaneBour/Torch/commit/fe08ffdc3a5dbbf489ab07dddf69d79ee7747be6))
*  **cache:** bump `illuminate` from 6.0 to 7.0 ([121afed](https://github.com/StephaneBour/Torch/commit/121afed2998fb9bc34aeeff2b6ad1e2ae07a2d40))
*  **cache:** bump `whoops` ([8a946b1](https://github.com/StephaneBour/Torch/commit/8a946b123e39878a684e0350ed7d942bd5ee695f))
*  **cache:** bump `predis/predis` from 1.0 to 1.1 ([2af01ad](https://github.com/StephaneBour/Torch/commit/2af01ad76ec730a6460dbdce9f2332465225d7c4))
*  **cache:** add parentheses ([6008c2f](https://github.com/StephaneBour/Torch/commit/6008c2f352fff44e99df9908860592a9b02dc004))
*  **config:** bump `illuminate/config` from 6.0 to 7.0 ([16a5cac](https://github.com/StephaneBour/Torch/commit/16a5cac4230a0eb6dcf06ff089ebd8508c298aac))
*  **config:** bump `filp/whoops` from 2.1.10 to 2.3.4 ([69afe5b](https://github.com/StephaneBour/Torch/commit/69afe5ba18406109e8c1a517c38cfefa0718dcb2))
*  **container:** bump `illuminate/container` from 6.0 yo 7.0 ([91698c3](https://github.com/StephaneBour/Torch/commit/91698c35ad7ae983516464c46664d0a4ea6aaa24))
*  **container:** bump slim from 2 to 3 and whoops ([30a2084](https://github.com/StephaneBour/Torch/commit/30a2084510e919598c7b4490b69c1bad4c0cdffd))
*  **database:** bump `illuminate/database` from 6.0 to 7.0 ([31d1e26](https://github.com/StephaneBour/Torch/commit/31d1e261af6fecdbe29fc54a6f7ff8526d611a1f))
*  **database:** bump `slim/slim` from 2 to 3 and whoops ([e4f5b43](https://github.com/StephaneBour/Torch/commit/e4f5b43a5551cc5a3b92845e96d7cbec07f2ce0d))
*  **encryption:** bump `illuminate/encryption` from 6.0 to 7.0 ([117af39](https://github.com/StephaneBour/Torch/commit/117af396fa2389f65830f9e5f33c42501f574a6c))
*  **encryption:** bump `filp/whoops` from 2.1.10 to 2.3.2 ([9ac4a99](https://github.com/StephaneBour/Torch/commit/9ac4a997608e846effe25f5a33db8dc0e8148cd4))
*  **events:** bump `illuminate/events` from 6.0 to 7.0 ([9670574](https://github.com/StephaneBour/Torch/commit/967057414d976b4234e4d94a00c359fe5ab29fc7))
*  **log:** bump `illuminate/log` from 6.0 to 7.0 ([9892094](https://github.com/StephaneBour/Torch/commit/98920945b43b987b8be7c8a74a0bb165794c559f))
*  **log:** bump `filp/whoops` from 2.1.10 to 2.3.2 ([f2aaa8c](https://github.com/StephaneBour/Torch/commit/f2aaa8c9688a48b658fee9a133757332d5272018))
*  **middleware:** bump illuminate routing and events from 6.0 to 7.0 ([e96a900](https://github.com/StephaneBour/Torch/commit/e96a90010245d02a87306481e0de3d306ac94565))
*  **pagination:** bump illuminate components from 6.0 to 7.0 ([17bb7b6](https://github.com/StephaneBour/Torch/commit/17bb7b67e0676d8fc4b4f607197bd91296fabb2d))
*  **pagination:** bump slim from 2 to 3 and whoops ([08c0b81](https://github.com/StephaneBour/Torch/commit/08c0b810efc80ed162e97242f72dbab600b1507d))
*  **queue:** bump illuminate components from 6 to 7 ([3691a1f](https://github.com/StephaneBour/Torch/commit/3691a1f264286b7ee155cf4ce3f609c15495181d))
*  **queue:** bump `slim/slim` from 2 to 3 and whoops ([113760e](https://github.com/StephaneBour/Torch/commit/113760e0233de48379bf70b5b1a2f2dde1d93e88))
*  **routing:** bump `illuminate/routing` from 6.0 to 7.0 ([4438725](https://github.com/StephaneBour/Torch/commit/443872595a907e771228cb14eb09bc96f4594cfe))
*  **session:** bump illuminate components from 6.0 to 7.0 ([cfa8223](https://github.com/StephaneBour/Torch/commit/cfa8223f68aaf0f1b9a65650dadd29967313489d))
*  **session:** bump `filp/whoops` from 2.1.10 to 2.3.2 ([39f30e8](https://github.com/StephaneBour/Torch/commit/39f30e885117a6c974603123f17486d9eaa08099))
*  **support:** bump `illuminate/support` from 6.0 to 7.0 ([7e861b9](https://github.com/StephaneBour/Torch/commit/7e861b989c9535d9fd243cde833ff9bfa06f2aef))
*  **support:** bump `filp/whoops` from 2.1.10 to 2.3.2 ([2f6facf](https://github.com/StephaneBour/Torch/commit/2f6facfbf989a7194479c8982cff729daaf026c1))
*  **translation:** bump `illuminate/translation` from 6.à to 7.0 ([dc07d9c](https://github.com/StephaneBour/Torch/commit/dc07d9c915803e28357d5f8a24f782cccf9dffa6))
*  **translation:** bump `slim/slim` from 2 to 3 and whoops ([9bf3763](https://github.com/StephaneBour/Torch/commit/9bf376335f0c692b3b8594c5ace59a665d6bf9a5))
*  **validation:** bump illuminate components from 6.0 to 7.0 ([70279ea](https://github.com/StephaneBour/Torch/commit/70279ea87b9dd12ddedd87d3b1c3333055217e66))
*  **view:** bump illuminate components from 6.0 to 7.0 ([28e3c4a](https://github.com/StephaneBour/Torch/commit/28e3c4a9a8f7f030c81e32f8352cf8e7427b8a5b))
*  **view:** bump `filp/whoops` from 2.1.10 to 2.3.2 ([e69359b](https://github.com/StephaneBour/Torch/commit/e69359b12a637f36da20fbfd96849b20623491a5))


### Features

*  **database:** use sqlite driver by default ([2661d9e](https://github.com/StephaneBour/Torch/commit/2661d9e4f4ba05b0f52fe2770b3058100a43f58f))
*  **pagination:** use sqlite driver and database by default ([8b9d322](https://github.com/StephaneBour/Torch/commit/8b9d322a240cf2b34f7b9a6f9120e0761b4ed33a))


### Code Refactoring

*  **validation:** bump `slim/slim` from 2 to 3 ([1fe5281](https://github.com/StephaneBour/Torch/commit/1fe52810b43fe288a21c23083bddf1db00849fa7))


### Documentation

*  **artisan:** update link for 7.x ([d8ca207](https://github.com/StephaneBour/Torch/commit/d8ca207299c79016670fcbe7fe2e0feb02f8d2d4))
*  **cache:** update link for 7.x ([2eb25dc](https://github.com/StephaneBour/Torch/commit/2eb25dcfec0b3fd176b485b1023223c79777577a))
*  **config:** update link for 7.x ([ad09a11](https://github.com/StephaneBour/Torch/commit/ad09a110aba9fb8e676e86a3b22bae1b5446ca7c))
*  **container:** update link for 7.x ([b6f4946](https://github.com/StephaneBour/Torch/commit/b6f49462897eb67c8877cd97e1df39994810f221))
*  **database:** update link for 7.x ([213eeeb](https://github.com/StephaneBour/Torch/commit/213eeebc3620c36d0f3cb49f6efb47c2dc16acf4))
*  **encryption:** update link for 7.x ([c2a9cd6](https://github.com/StephaneBour/Torch/commit/c2a9cd617ee6e565d30a9deafabdc9fe8bc9114a))
*  **events:** update link for 7.x ([5241128](https://github.com/StephaneBour/Torch/commit/52411282646f08ff821d288a01064f23c2910816))
*  **log:** update link for 7.x ([d9cca28](https://github.com/StephaneBour/Torch/commit/d9cca28fc610469cd48806792561d52216eadebf))
*  **middleware:** update link for 7.x ([9ad7ffe](https://github.com/StephaneBour/Torch/commit/9ad7ffebbd5e4d5d8300a477808506f2bcabecfa))
*  **pagination:** update link for 7.x ([8f0b4df](https://github.com/StephaneBour/Torch/commit/8f0b4df3aeaa581d26aaa4661328f41f6a1fa9c9))
*  **queue:** update link for 7.x ([55d144f](https://github.com/StephaneBour/Torch/commit/55d144f869a1c41fd1a9447804d2c3adcfff3ca3))
*  **routing:** update link for 7.x ([496ce3d](https://github.com/StephaneBour/Torch/commit/496ce3dd32e2d9ccfdc351822cb45ea480df2be3))
*  **session:** update link for 7.x ([8831be1](https://github.com/StephaneBour/Torch/commit/8831be1dadafc456c359972b69f1d34641a069da))
*  **support:** update links for 7.x ([b65f0cc](https://github.com/StephaneBour/Torch/commit/b65f0cc250fcf010b50639fbcc4d191077a41f4a))
*  **translation:** update link for 7.x ([bb584af](https://github.com/StephaneBour/Torch/commit/bb584affbc9e346f88a6d883de6e472277a7acfd))
*  **validation:** update link for 7.x ([3114578](https://github.com/StephaneBour/Torch/commit/3114578cf694bdf80e302f97aec2a063f127f6e9))
*  **view:** update link for 7.x ([40385c5](https://github.com/StephaneBour/Torch/commit/40385c56d831044fbbf18bfd7b8ebdf347227270))
*  **readme:** update for 7.0 ([c140791](https://github.com/StephaneBour/Torch/commit/c1407913c909ddd993f40be701ffe9407752d385))

**Comment by StephaneBour** [comment]
@mattstauffer : hello, any comments?

**Comment by mattstauffer** [comment]
@StephaneBour WHOA. Thank you for your hard work! I didn't even see this!!

**Comment by mattstauffer** [comment]
@StephaneBour BTW I remember this is here. I promise I'm looking at it ASAP.

**Comment by mattstauffer** [comment]
@StephaneBour I can't thank you enough for your hard work on this!!

**Pull request merged**
