### PR TITLE
adding log component

### PR DESCRIPTION
**Pull request by carousel**
hi Matt, 
here is my contribution to your awesome Torch project with log component.

### CODE REVIEW

**Comment by carousel** [comment]
running php-cs-fixer

**Comment by GrahamCampbell** [comment]
> running php-cs-fixer

Could have been avoided by just using StyleCI. :troll:

**Comment by mattstauffer** [comment]
Classy, @GrahamCampbell.

**Comment by mattstauffer** [comment]
@carousel Please take a look at the remaining code style changes to get this in line with PSR-2, and then I'd love to review it. Thanks for your work!

**Comment by carousel** [comment]
Applied fixes with StyleCI (to make it PSR-2 compatible).

**Comment by mattstauffer** [comment]
@carousel sorry to be a jerk, but the StyleCI bot is wrong in almost every case. It actually made this code worse rather than better.

**Comment by mattstauffer** [comment]
@carousel do you know how to to revert a commit? If so, please revert the StyleCI commit. If not, I will need to take it and un-do that and then apply the correct PSR-2 stuff. Let me know. Thanks!

**Comment by GrahamCampbell** [comment]
HAHA. It's only wrong if you configure it wrongly. You just need to enable only the PSR2 rules on StyleCI and you're sorted. Also, I didn't expect you to actually use StyleCI just now! I was just having a bit of fun with you. ;)

**Comment by mattstauffer** [comment]
@carousel Sorry to be a pain, but would you be willing to re-create this pull request with just the `log` files? Let me fix the code style, don't worry about php-cs-fixer or styleci. 

If you'd rather not, let me know and i'll do it myself, but that way you won't get commit credit, so I want to give you the chance to do it first if you'd like.

**Comment by mattstauffer** [comment]
@carousel Thanks for your contribution! I was able to pick just your original commit.

https://github.com/mattstauffer/Torch/tree/master/components/log

Thanks!

**Pull request closed without merging**
