### PR TITLE
[WIP] Artisan Component

### PR DESCRIPTION
**Pull request by hskrasek**
Opening this early for discussion/question asking. Trying to work on the artisan component, the main issue at the moment is that `composer require illuminate/foundation` fails, and the main thing we need is the foundation app. 

You can get around this by rewriting chunk of artisan, but I feel like that's against the "spirit" of what this project is trying to accomplish.

### CODE REVIEW

**Comment by hskrasek** [comment]
@mattstauffer Any input on this one? I kinda hit a brick wall here :disappointed:

**Comment by mattstauffer** [comment]
@hskrasek Sorry, don't know why I didn't look at it. What's going wrong when requiring `foundation`?

**Comment by hskrasek** [comment]
@mattstauffer I get the following:

```bash
$ composer require illuminate/foundation
Loading composer repositories with package information
Updating dependencies (including require-dev)
....
- Installing illuminate/foundation (v1.1.2)
    Downloading: Connecting...    Failed to download illuminate/foundation from dist: The "https://api.github.com/repos/illuminate/foundation/zipball/d9d9218972b653d46e7dfea14e8773cbb5d5451a" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing illuminate/foundation (v1.1.2)
    Cloning d9d9218972b653d46e7dfea14e8773cbb5d5451a

Installation failed, deleting ./composer.json.


  [RuntimeException]
  Failed to clone https://github.com/illuminate/foundation.git via https, ssh protocols, aborting.
  - https://github.com/illuminate/foundation.git
    Cloning into '/Users/hunterskrasek/Documents/Personal/IlluminateNonLaravel/vendor/illuminate/foundation'...
    remote: Repository not found.
    fatal: repository 'https://github.com/illuminate/foundation.git/' not found
  - git@github.com:illuminate/foundation.git
    Cloning into '/Users/hunterskrasek/Documents/Personal/IlluminateNonLaravel/vendor/illuminate/foundation'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```

If you look here: https://github.com/laravel/framework/tree/5.2/src/Illuminate/Foundation there is not composer.json file, and on packagist it shows up as abandonded after 4.* https://packagist.org/packages/illuminate/foundation

**Comment by iowillhoit** [comment]
Afternoon gentlemen,
I ran into this same issue, have you been able to make any progress? 
We use Symfony's Console Component a lot at work and I would love to be able to harness the syntax of Artisan.

**Comment by huglester** [comment]
Hello

maybe there are news here? :)

**Comment by dead23angel** [comment]
@huglester I think this feature is not worth the wait

**Comment by webstractions** [comment]
@hskrasek 

>  the main thing we need is the foundation app.

That is not necessarily true. I think at a minimum is an instance of the console kernel which the foundation app builds for you. Don't need an app for that!

**Comment by deleugpn** [comment]
Maybe it's worth to take a look at [Laravel Zero](https://github.com/laravel-zero/laravel-zero)

**Comment by hskrasek** [comment]
So looking into how Laravel Zero works, it's basically what this repo aims to offer. You'd have to do a ton of custom code to make "artisan" work outside of a laravel install and that is exactly what Laravel Zero does. 

@mattstauffer Not sure how you'd want to handle this, but I'd recommend linking to Laravel Zero on how to get Artisan working outside of an install. Otherwise I bet I could hack together a very ugly but working example

**Comment by hskrasek** [comment]
@mattstauffer Looks like you got an artisan component already setup, which is awesome! I'm gonna clean this up and close out

**Pull request closed without merging**
