### PR TITLE
Started porting components to 5.5

### PR DESCRIPTION
**Pull request by Rubemlrm**
Started porting components to 5.5.
Already ported the following components:

- Logs
- Config
- Encryption

Working on more components in the following days.

### CODE REVIEW

**Comment by mattstauffer** [comment]
@Rubemlrm OK, so you tested each of these and they worked fine?

Also, if we're going to be updating them to 5.5, we'll want to somehow A) note it in the readme and B) make it easy (a link to a commit, or a branch, or something?) to get back to it.

Maybe just like I did with 4.2 we branch 5.1 off of master, and then master will now be 5.5 and we'll track which we have and haven't moved over to 5.5 

Thoughts?

**Comment by dead23angel** [comment]
I suggest removing the components of version 5.1 from master to a separate branch, and in master, place the components 5.5

**Comment by Rubemlrm** [comment]
Hi there @mattstauffer,

I've been testing each component, my ideia was having a branch only to 5.5 components until i have all migrated to 5.5 and after that change to a master template. But in the pull request i can't create a new branch and because of that i've pull request to this one. Sorry if i've made a bad decision relative to this.

**Comment by mattstauffer** [comment]
@Rubemlrm Naw, let me do a bit of branching strategy and get back to you in a few minutes.

**Comment by Rubemlrm** [comment]
@mattstauffer roger that =) i will be waiting.

**Comment by mattstauffer** [comment]
@Rubemlrm OK, just made `master` equal to 5.5. You can see how i updated the `readme` to point to the components you've tested and updated.

Thanks!

**Comment by Rubemlrm** [comment]
Just checked the new readme , i will provide more components in minutes =)

**Pull request merged**
